---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo-app
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - dev
                - prod
  template:
    metadata:
      name: 'todo-app-{{name}}'
      labels:
        app.kubernetes.io/managed-by: acm
    spec:
      project: default
      source:
        repoURL: https://github.com/CSA-RH/acm_apps_demo1-appset_push_model.git
        targetRevision: main
        path: 'kustomize/overlays/{{metadata.labels.environment}}'
      destination:
        server: '{{server}}'
        namespace: todo-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
